name: flutter_clean_architecture
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Architecture
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9

  # Firebase & Google Services
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_crashlytics: ^4.1.3
  firebase_database: ^11.1.4
  firebase_dynamic_links: ^6.0.8
  firebase_messaging: ^15.1.3
  firebase_remote_config: ^5.1.3
  firebase_storage: ^12.3.2
  firebase_app_check: ^0.3.1+3
  firebase_performance: ^0.10.0+8

  # Notifications & Toasts
  flutter_local_notifications: ^19.3.0
  fluttertoast: ^8.2.12

  # Networking
  dio: ^5.7.0
  http: ^1.4.0
  retrofit: ^4.4.1
  ua_client_hints: ^1.2.2

  # Serialization & Models
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  equatable: ^2.0.5
  meta: ^1.15.0

  # Navigation
  auto_route: ^9.2.0
  auto_route_generator: ^9.0.0

  # UI Components
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  chewie: ^1.7.5
  extended_text_field: ^16.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.6
  flutter_picker_plus: ^1.3.0
  flutter_sfsymbols: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_cache_manager: ^3.3.1
  gap: ^3.0.1
  photo_view: ^0.15.0
  pinput: ^5.0.1
  scrollable_positioned_list: ^0.3.8
  selectable_autolink_text: ^2.6.0
  table_calendar: ^3.0.9
  visibility_detector: ^0.4.0

  # Video & Audio
  better_player:
    git:
      url: https://github.com/thatera-howard-nguyen/better-player-ultra.git
      ref: master
  video_player: ^2.8.3
  youtube_player_iframe: ^5.2.0
  audio_session: ^0.2.2
  haishin_kit: ^0.14.3
  video_thumbnail: ^0.5.3

  # WebView
  webview_flutter: ^4.7.0
  webview_flutter_wkwebview: ^3.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_platform_interface: ^2.10.0

  # Map & Location
  map_launcher: ^3.3.0
  flutter_map: ^8.1.1

  # Camera & Gallery
  camera: ^0.11.1
  bindings_compatible: ^1.0.1
  camera_platform_interface: ^2.7.4
  path: ^1.9.0
  path_provider: ^2.1.2
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+21
  image_picker_platform_interface: ^2.10.1
  image_gallery_saver_plus: ^4.0.1
  photo_manager: ^3.0.0-dev.5
  photo_manager_image_provider: ^2.1.1
  wakelock_plus: ^1.2.8
  permission_handler: ^12.0.0+1

  # In-App Purchase
  in_app_purchase: ^3.1.13
  in_app_purchase_android: ^0.4.0+2
  in_app_purchase_storekit: ^0.4.2

  # Utilities
  async: ^2.11.0
  collection: ^1.18.0
  device_info_plus: ^11.3.0
  android_id: ^0.4.0
  intl: ^0.19.0
  metadata_fetch: ^0.4.1
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  share_plus: ^11.0.0
  shared_preferences: ^2.2.2
  native_shared_preferences: ^2.0.9
  flutter_keychain: ^2.4.0
  app_badge_plus: ^1.2.3
  screen_protector: ^1.4.2
  social_sharing_plus: ^1.2.3
  version: ^3.0.2
  package_info_plus: ^8.0.3
  stack_trace: ^1.11.1

  # Encryption
  encrypt: ^5.0.3

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Animation
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  retrofit_generator: ^9.2.0
  hive_generator: ^2.0.1
  custom_lint:
  flutter_lints:
  flutter_hooks_lint:
  import_sorter: ^4.6.0

dependency_overrides:
  custom_lint_core: ^0.6.4

import_sorter:
  emojis: false
  comments: false

flutter_gen:
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/icon/social/
    - assets/image/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Light.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Thin.otf
    - family: NotoSerifJP
      fonts:
        - asset: assets/fonts/NotoSerifJP-Black.otf
